services:

  db:
    build:
      context: ./database
      dockerfile: my.Dockerfile
    container_name: delivery_mysql
    restart: always
    volumes:
      - ./database/mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-uroot", "-${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    env_file:
      - .env

  prestart:
    image: delivery-prestart
    build:
      context: ./backend
    networks:
      - default
    depends_on:
      db:
        condition: service_healthy
    command: bash scripts/prestart.sh
    env_file:
      - .env
#    environment:
#      - DOMAIN=${DOMAIN}
#      - ENVIRONMENT=${ENVIRONMENT}
#      - SECRET_KEY=${SECRET_KEY?Variable not set}
#      - FIRST_SUPERUSER=${FIRST_SUPERUSER?Variable not set}
#      - FIRST_SUPERUSER_PASSWORD=${FIRST_SUPERUSER_PASSWORD?Variable not set}
#      - MYSQL_SERVER=db
#      - MYSQL_PORT=${MYSQL_PORT}
#      - MYSQL_DB=${MYSQL_DB}
#      - MYSQL_USER=${MYSQL_USER?Variable not set}
#      - MYSQL_PASSWORD=${MYSQL_PASSWORD?Variable not set}

  backend:
    image: delivery-backend
    restart: always
    networks:
      - default
    depends_on:
      db:
        condition: service_healthy
      prestart:
        condition: service_completed_successfully
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v1/utils/health-check/" ]
      interval: 10s
      timeout: 5s
      retries: 5

    build:
      context: ./backend
#    environment:
#      - DOMAIN=${DOMAIN}
#      - ENVIRONMENT=${ENVIRONMENT}
#      - SECRET_KEY=${SECRET_KEY?Variable not set}
#      - FIRST_SUPERUSER=${FIRST_SUPERUSER?Variable not set}
#      - FIRST_SUPERUSER_PASSWORD=${FIRST_SUPERUSER_PASSWORD?Variable not set}
#      - MYSQL_SERVER=db
#      - MYSQL_PORT=${MYSQL_PORT}
#      - MYSQL_DB=${MYSQL_DB}
#      - MYSQL_USER=${MYSQL_USER?Variable not set}
#      - MYSQL_PASSWORD=${MYSQL_PASSWORD?Variable not set}

  periodic_tasks:
    image: delivery-periodic-tasks
    build:
      context: ./backend
    networks:
      - default
    depends_on:
      db:
        condition: service_healthy
      prestart:
        condition: service_completed_successfully

    command: bash scripts/periodic-tasks.sh
    env_file:
      - .env
#    environment:
#      - DOMAIN=${DOMAIN}
#      - ENVIRONMENT=${ENVIRONMENT}
#      - SECRET_KEY=${SECRET_KEY?Variable not set}
#      - FIRST_SUPERUSER=${FIRST_SUPERUSER?Variable not set}
#      - FIRST_SUPERUSER_PASSWORD=${FIRST_SUPERUSER_PASSWORD?Variable not set}
#      - MYSQL_SERVER=db
#      - MYSQL_PORT=${MYSQL_PORT}
#      - MYSQL_DB=${MYSQL_DB}
#      - MYSQL_USER=${MYSQL_USER?Variable not set}
#      - MYSQL_PASSWORD=${MYSQL_PASSWORD?Variable not set}


  redis:
    image: redis:8.0-M02-bookworm
    restart: always
    container_name: delivery-redis
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 10s
      timeout: 5s
      retries: 5

#  rabbitmq:
#    image: rabbitmq:4.0.5-management
#    container_name: delivery-rabbitmq
#    restart: always

volumes:
  app-db-data:
