"""Initial revision

Revision ID: 04a8e2a258de
Revises: 
Create Date: 2025-01-04 08:46:40.665053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04a8e2a258de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliverytypes',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliverytypes')),
    sa.UniqueConstraint('name', name=op.f('uq_deliverytypes_name'))
    )
    op.create_table('users',
    sa.Column('session', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_session'), 'users', ['session'], unique=True)
    op.create_table('deliverys',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('cost_of_content_usd', sa.Float(), nullable=False),
    sa.Column('cost_of_delivery_rub', sa.Float(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['deliverytypes.id'], name=op.f('fk_deliverys_type_id_deliverytypes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_deliverys_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliverys'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deliverys')
    op.drop_index(op.f('ix_users_session'), table_name='users')
    op.drop_table('users')
    op.drop_table('deliverytypes')
    # ### end Alembic commands ###
