"""Clickhouse

Revision ID: cf78142d6a2b
Revises: 0ca83a793b71
Create Date: 2025-01-11 09:26:25.776027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf78142d6a2b'
down_revision: Union[str, None] = '0ca83a793b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliverys', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('deliverys', sa.Column('is_pushed_to_clickhouse', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliverys', 'is_pushed_to_clickhouse')
    op.drop_column('deliverys', 'created_at')
    # ### end Alembic commands ###
